spring.application.name=be-cadelfriul

# --- CONFIGURAZIONE DATABASE POSTGRESQL ---
spring.datasource.url=jdbc:postgresql://localhost:5432/cadelfriul_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate (lo strumento che gestisce le tabelle)
# 'update' dice a Spring di creare le tabelle nel database automaticamente se non esistono
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- CONFIGURAZIONE SERVER ---
# La porta su cui girerà il backend Java
server.port=8080